version: "3.8"
services:
  backend:
    image: felixchimaa/backend:latest
    container_name: backend
    expose:
      - "5000"             # Internal only
    restart: unless-stopped

  frontend:
    image: felixchimaa/frontend:latest
    container_name: frontend
    ports:
      - "80:80"             # <-- Serve this on public port 80
    depends_on:
      - backend
    restart: unless-stopped
