name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VM_HOST: ${{ secrets.VM_HOST }}
      VM_USER: ${{ secrets.VM_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build and push backend
        run: |
          docker build -t $DOCKERHUB_USERNAME/backend:latest ./backend
          docker push $DOCKERHUB_USERNAME/backend:latest

      - name: Build and push frontend
        run: |
          docker build -t $DOCKERHUB_USERNAME/frontend:latest ./frontend
          docker push $DOCKERHUB_USERNAME/frontend:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_HOST }}
          username: ${{ env.VM_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            docker pull $DOCKERHUB_USERNAME/backend:latest
            docker pull $DOCKERHUB_USERNAME/frontend:latest
            cd /path/to/your/docker-compose
            docker-compose down
            docker-compose up -d
